### ISSUE TITLE
Multiple pages not found (404)

### ISSUE THREAD

**Issue by quassy** [aleksandar-todorovic/r3bl.me#1]
Clicking on [Aleksandar Todorović](https://r3bl.me/contact) leads to a dead end, it should point to `https://r3bl.me/contact.html`. Also when using [W3C Link Checker](https://validator.w3.org/checklink?uri=https%3A%2F%2Fr3bl.me%2F&hide_type=all&depth=&check=Check) multiple other links turn out to be dead.

**Comment by aleksandar-todorovic** [comment]
Thanks for reporting! Moving the website around and upgrading the Jekyll version apparently broke things that weren't broken before. Most of it is fixed now.
